version: '2'

services:
    nginx: 
        container_name: nginx
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/development/Dockerfile
        ports:
            - 80:80
        volumes:
            - static_volume:/app/backend/server/django_static
            - ./docker/nginx/development:/etc/nginx/conf.d
        depends_on: 
            - backend
    backend:
        container_name: backend
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        environment:
            - DJANGO_SETTINGS_MODULE=brawlbackend.settings.dev_settings
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app:delegated
            - static_volume:/app/backend/server/django_static
        expose:
            - 8000    
        stdin_open: true
        tty: true
    
    frontend:
        container_name: frontend
        ports:
            - "3000:3080"
        build:
            context: ./
            dockerfile: ./docker/frontend/Dockerfile
        volumes:
            - ./frontend:/app:delegated
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        command: npm start
    postgres:
        container_name: postgres
        image: postgres:11.5-alpine
        environment:
        - POSTGRES_PASSWORD=brawlbay
        - POSTGRES_USER=postgres
        - POSTGRES_DB=brawlbay
        volumes:
        - pg_data:/var/lib/postgresql/data
        ports:
        - "5433:5432"

volumes:
    static_volume: {}
    pg_data: 