version: "3.9"
   
services:
  nginx:
    container_name: nginx
    image: nginx:1.18.0
    volumes:
      - .:/code
    depends_on:
      - django

  django:
    container_name: django
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/code:delegated
      - /code/node_modules
    command: npm run build

volumes:
  pg_data: