version: "3.9"
   
services:
  nginx:
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
      - frontend

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

  django:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8010
    volumes:
      - .:/code
    ports:
      - "8010:8010"
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    ports:
      - "3000:3000"
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/code:delegated
      - /code/node_modules
    command: npm run start

volumes:
  pg_data: