version: "3.9"
   
services:
  nginx:
    container_name: nginx
    image: nginx:1.18.0
    volumes:
      - .:/code
      - frontend_static:/etc/nginx/html/frontend_static
    depends_on:
      - django

  django:
    container_name: django
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - .:/code

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/code:delegated
      - /code/node_modules
      - frontend_static:/code/build
    environment:
      - NODE_ENV=production
    command: npm run build

volumes:
  frontend_static: