# Generated by Django 3.0.8 on 2020-09-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrawlhallaClan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clan_id", models.IntegerField(unique=True)),
                ("clan_name", models.CharField(max_length=64)),
                ("clan_create_date", models.DateTimeField()),
                ("clan_xp", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BrawlhallaLegend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legend_id", models.IntegerField(unique=True)),
                ("legend_name", models.CharField(max_length=32)),
                ("bio_name", models.CharField(max_length=32)),
                ("bio_aka", models.CharField(max_length=255)),
                ("bio_quote", models.TextField()),
                ("bio_quote_about_attrib", models.TextField()),
                ("bio_quote_from", models.TextField()),
                ("bio_quote_from_attrib", models.TextField()),
                ("bio_text", models.TextField()),
                ("bot_name", models.CharField(max_length=32)),
                ("weapon_one", models.CharField(max_length=32)),
                ("weapon_two", models.CharField(max_length=32)),
                ("strength", models.IntegerField()),
                ("dexterity", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("speed", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BrawlhallaPlayerRanked",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("peak_rating", models.IntegerField()),
                ("tier", models.CharField(max_length=32)),
                ("wins", models.IntegerField()),
                ("games", models.IntegerField()),
                ("region", models.CharField(max_length=16)),
                ("global_rank", models.IntegerField()),
                ("region_rank", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BrawlhallaUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brawlhalla_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=64)),
                ("xp", models.IntegerField()),
                ("level", models.IntegerField()),
                (
                    "xp_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("games", models.IntegerField()),
                ("wins", models.IntegerField()),
                ("damage_bomb", models.IntegerField()),
                ("damage_mine", models.IntegerField()),
                ("damage_spikeball", models.IntegerField()),
                ("damage_sidekick", models.IntegerField()),
                ("hit_snowball", models.IntegerField()),
                ("ko_bomb", models.IntegerField()),
                ("ko_spike", models.IntegerField()),
                ("ko_sidekick", models.IntegerField()),
                ("ko_snowball", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BrawlhallaPlayerRankedLegend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("peak_rating", models.IntegerField()),
                ("tier", models.CharField(max_length=32)),
                ("wins", models.IntegerField()),
                ("games", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranked",
                        to="brawlhalla.BrawlhallaLegend",
                    ),
                ),
                (
                    "ranked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legends",
                        to="brawlhalla.BrawlhallaPlayerRanked",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brawlhallaplayerranked",
            name="brawlhalla_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranked",
                to="brawlhalla.BrawlhallaUser",
            ),
        ),
        migrations.CreateModel(
            name="BrawlhallaPlayerLegend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage_dealt", models.IntegerField()),
                ("damage_taken", models.IntegerField()),
                ("kos", models.IntegerField()),
                ("falls", models.IntegerField()),
                ("suicides", models.IntegerField()),
                ("team_kos", models.IntegerField()),
                ("match_time", models.IntegerField()),
                ("games", models.IntegerField()),
                ("wins", models.IntegerField()),
                ("damage_unarmed", models.IntegerField()),
                ("damage_thrown", models.IntegerField()),
                ("damage_weapon_one", models.IntegerField()),
                ("damage_weapon_two", models.IntegerField()),
                ("damage_gadgets", models.IntegerField()),
                ("ko_unarmed", models.IntegerField()),
                ("ko_thrown", models.IntegerField()),
                ("ko_weapon_one", models.IntegerField()),
                ("ko_weapon_two", models.IntegerField()),
                ("ko_gadgets", models.IntegerField()),
                ("time_held_weapon_one", models.IntegerField()),
                ("time_held_weapon_two", models.IntegerField()),
                ("xp", models.IntegerField()),
                ("level", models.IntegerField()),
                (
                    "xp_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brawlhalla_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legends",
                        to="brawlhalla.BrawlhallaUser",
                    ),
                ),
                (
                    "legend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="played_legends",
                        to="brawlhalla.BrawlhallaLegend",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrawlhallaClanUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.CharField(max_length=32)),
                ("join_date", models.DateTimeField()),
                ("xp", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clan_members",
                        to="brawlhalla.BrawlhallaClan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clan_profile",
                        to="brawlhalla.BrawlhallaUser",
                    ),
                ),
            ],
        ),
    ]
