# Generated by Django 3.0.8 on 2021-01-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawlhalla', '0003_brawlhallaplayerrankedteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brawlhallaplayerrankedteam',
            name='brawlhalla_player_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='brawlhallaplayerrankedteam',
            name='brawlhalla_player_2',
            field=models.IntegerField(),
        ),
    ]
